version: "3"
services:
  pitch:
    image: store/gitpitch/desktop:pro
    volumes:
      - ./:/repo
    ports:
      - 9000:9000

  node:
    image: node:latest
    volumes:
      - ./:/app
    working_dir: /app

  presenter:
    image: node:latest
    volumes:
      - ./:/app
    environment:
      MEETUP: ${MEETUP}
    working_dir: /app
    command: ["node", "scripts/presenter.js", $MEETUP]
